/********************************************************************************
** Form generated from reading UI file 'my_risk.ui'
**
** Created by: Qt User Interface Compiler version 5.6.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MY_RISK_H
#define UI_MY_RISK_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_my_riskClass
{
public:
    QWidget *centralWidget;
    QLabel *label;
    QPushButton *south_america_1;
    QPushButton *south_america_2;
    QPushButton *south_america_3;
    QPushButton *south_america_4;
    QPushButton *north_america_1;
    QPushButton *north_america_2;
    QPushButton *north_america_3;
    QPushButton *north_america_4;
    QPushButton *north_america_5;
    QPushButton *north_america_6;
    QPushButton *north_america_7;
    QPushButton *north_america_8;
    QPushButton *north_america_9;
    QPushButton *africa;
    QPushButton *africa_2;
    QPushButton *africa_3;
    QPushButton *africa_4;
    QPushButton *africa_5;
    QPushButton *africa_6;
    QPushButton *europe_1;
    QPushButton *europe_2;
    QPushButton *europe_3;
    QPushButton *europe_4;
    QPushButton *europe_5;
    QPushButton *europe_6;
    QPushButton *europe_7;
    QPushButton *australia;
    QPushButton *australia_2;
    QPushButton *australia_3;
    QPushButton *australia_4;
    QPushButton *asia;
    QPushButton *asia_2;
    QPushButton *asia_3;
    QPushButton *asia_4;
    QPushButton *asia_5;
    QPushButton *asia_6;
    QPushButton *asia_7;
    QPushButton *asia_8;
    QPushButton *asia_9;
    QPushButton *asia_10;
    QPushButton *asia_11;
    QTextEdit *textEdit;
    QPushButton *ENTER;
    QPushButton *SAVE;
    QLabel *colorP;
    QPushButton *NEXT;
    QGroupBox *TROOPS;
    QPushButton *MINUS;
    QPushButton *PLUS;
    QTextEdit *troopsP;
    QGroupBox *groupBox;
    QPushButton *card1;
    QPushButton *card2;
    QPushButton *card3;
    QPushButton *card4;
    QPushButton *card5;
    QGroupBox *TROOPS_2;
    QPushButton *MINUS_2;
    QPushButton *PLUS_2;
    QTextEdit *troopsP_2;
    QLabel *cubeP_1;
    QLabel *cubeP_2;
    QLabel *cubeP2_1;
    QLabel *cubeP2_2;
    QLabel *cubeP_3;
    QLabel *cubeP2_3;
    QPushButton *CONVERT;
    QTextEdit *playerText;
    QTextEdit *stageText;
    QPushButton *STATS;
    QPushButton *SAVE_ALL;
    QPushButton *EXIT;
    QPushButton *asia_12;
    QLabel *value_cards;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *my_riskClass)
    {
        if (my_riskClass->objectName().isEmpty())
            my_riskClass->setObjectName(QStringLiteral("my_riskClass"));
        my_riskClass->resize(1464, 866);
        my_riskClass->setStyleSheet(QStringLiteral("background-image: url(':/risk_map')"));
        centralWidget = new QWidget(my_riskClass);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(0, 0, 1201, 811));
        label->setStyleSheet(QStringLiteral(""));
        label->setPixmap(QPixmap(QString::fromUtf8(":/new/Resources/risk_map.png")));
        label->setScaledContents(true);
        south_america_1 = new QPushButton(centralWidget);
        south_america_1->setObjectName(QStringLiteral("south_america_1"));
        south_america_1->setGeometry(QRect(290, 500, 31, 21));
        QFont font;
        font.setFamily(QStringLiteral("Rockwell"));
        font.setPointSize(11);
        font.setBold(true);
        font.setItalic(false);
        font.setWeight(75);
        south_america_1->setFont(font);
        south_america_1->setCursor(QCursor(Qt::PointingHandCursor));
        south_america_1->setAcceptDrops(false);
        south_america_1->setAutoFillBackground(true);
        south_america_1->setStyleSheet(QStringLiteral(""));
        south_america_1->setInputMethodHints(Qt::ImhNone);
        south_america_1->setAutoRepeat(false);
        south_america_1->setAutoExclusive(false);
        south_america_2 = new QPushButton(centralWidget);
        south_america_2->setObjectName(QStringLiteral("south_america_2"));
        south_america_2->setGeometry(QRect(350, 550, 31, 21));
        south_america_2->setFont(font);
        south_america_2->setCursor(QCursor(Qt::PointingHandCursor));
        south_america_2->setAcceptDrops(false);
        south_america_2->setAutoFillBackground(true);
        south_america_2->setStyleSheet(QStringLiteral(""));
        south_america_2->setInputMethodHints(Qt::ImhNone);
        south_america_2->setAutoRepeat(false);
        south_america_2->setAutoExclusive(false);
        south_america_3 = new QPushButton(centralWidget);
        south_america_3->setObjectName(QStringLiteral("south_america_3"));
        south_america_3->setGeometry(QRect(300, 550, 31, 21));
        south_america_3->setFont(font);
        south_america_3->setCursor(QCursor(Qt::PointingHandCursor));
        south_america_3->setAcceptDrops(false);
        south_america_3->setAutoFillBackground(true);
        south_america_3->setStyleSheet(QStringLiteral(""));
        south_america_3->setInputMethodHints(Qt::ImhNone);
        south_america_3->setAutoRepeat(false);
        south_america_3->setAutoExclusive(false);
        south_america_4 = new QPushButton(centralWidget);
        south_america_4->setObjectName(QStringLiteral("south_america_4"));
        south_america_4->setGeometry(QRect(330, 680, 31, 21));
        south_america_4->setFont(font);
        south_america_4->setCursor(QCursor(Qt::PointingHandCursor));
        south_america_4->setAcceptDrops(false);
        south_america_4->setAutoFillBackground(true);
        south_america_4->setStyleSheet(QStringLiteral(""));
        south_america_4->setInputMethodHints(Qt::ImhNone);
        south_america_4->setAutoRepeat(false);
        south_america_4->setAutoExclusive(false);
        north_america_1 = new QPushButton(centralWidget);
        north_america_1->setObjectName(QStringLiteral("north_america_1"));
        north_america_1->setGeometry(QRect(50, 110, 31, 21));
        north_america_1->setFont(font);
        north_america_1->setCursor(QCursor(Qt::PointingHandCursor));
        north_america_1->setAcceptDrops(false);
        north_america_1->setAutoFillBackground(true);
        north_america_1->setStyleSheet(QStringLiteral(""));
        north_america_1->setInputMethodHints(Qt::ImhNone);
        north_america_1->setAutoRepeat(false);
        north_america_1->setAutoExclusive(false);
        north_america_2 = new QPushButton(centralWidget);
        north_america_2->setObjectName(QStringLiteral("north_america_2"));
        north_america_2->setGeometry(QRect(120, 110, 31, 21));
        north_america_2->setFont(font);
        north_america_2->setCursor(QCursor(Qt::PointingHandCursor));
        north_america_2->setAcceptDrops(false);
        north_america_2->setAutoFillBackground(true);
        north_america_2->setStyleSheet(QStringLiteral(""));
        north_america_2->setInputMethodHints(Qt::ImhNone);
        north_america_2->setAutoRepeat(false);
        north_america_2->setAutoExclusive(false);
        north_america_3 = new QPushButton(centralWidget);
        north_america_3->setObjectName(QStringLiteral("north_america_3"));
        north_america_3->setGeometry(QRect(340, 130, 31, 21));
        north_america_3->setFont(font);
        north_america_3->setCursor(QCursor(Qt::PointingHandCursor));
        north_america_3->setAcceptDrops(false);
        north_america_3->setAutoFillBackground(true);
        north_america_3->setStyleSheet(QStringLiteral(""));
        north_america_3->setInputMethodHints(Qt::ImhNone);
        north_america_3->setAutoRepeat(false);
        north_america_3->setAutoExclusive(false);
        north_america_4 = new QPushButton(centralWidget);
        north_america_4->setObjectName(QStringLiteral("north_america_4"));
        north_america_4->setGeometry(QRect(120, 220, 31, 21));
        north_america_4->setFont(font);
        north_america_4->setCursor(QCursor(Qt::PointingHandCursor));
        north_america_4->setAcceptDrops(false);
        north_america_4->setAutoFillBackground(true);
        north_america_4->setStyleSheet(QStringLiteral(""));
        north_america_4->setInputMethodHints(Qt::ImhNone);
        north_america_4->setAutoRepeat(false);
        north_america_4->setAutoExclusive(false);
        north_america_5 = new QPushButton(centralWidget);
        north_america_5->setObjectName(QStringLiteral("north_america_5"));
        north_america_5->setGeometry(QRect(180, 240, 31, 21));
        north_america_5->setFont(font);
        north_america_5->setCursor(QCursor(Qt::PointingHandCursor));
        north_america_5->setAcceptDrops(false);
        north_america_5->setAutoFillBackground(true);
        north_america_5->setStyleSheet(QStringLiteral(""));
        north_america_5->setInputMethodHints(Qt::ImhNone);
        north_america_5->setAutoRepeat(false);
        north_america_5->setAutoExclusive(false);
        north_america_6 = new QPushButton(centralWidget);
        north_america_6->setObjectName(QStringLiteral("north_america_6"));
        north_america_6->setGeometry(QRect(250, 250, 31, 21));
        north_america_6->setFont(font);
        north_america_6->setCursor(QCursor(Qt::PointingHandCursor));
        north_america_6->setAcceptDrops(false);
        north_america_6->setAutoFillBackground(true);
        north_america_6->setStyleSheet(QStringLiteral(""));
        north_america_6->setInputMethodHints(Qt::ImhNone);
        north_america_6->setAutoRepeat(false);
        north_america_6->setAutoExclusive(false);
        north_america_7 = new QPushButton(centralWidget);
        north_america_7->setObjectName(QStringLiteral("north_america_7"));
        north_america_7->setGeometry(QRect(130, 330, 31, 21));
        north_america_7->setFont(font);
        north_america_7->setCursor(QCursor(Qt::PointingHandCursor));
        north_america_7->setAcceptDrops(false);
        north_america_7->setAutoFillBackground(true);
        north_america_7->setStyleSheet(QStringLiteral(""));
        north_america_7->setInputMethodHints(Qt::ImhNone);
        north_america_7->setAutoRepeat(false);
        north_america_7->setAutoExclusive(false);
        north_america_8 = new QPushButton(centralWidget);
        north_america_8->setObjectName(QStringLiteral("north_america_8"));
        north_america_8->setGeometry(QRect(210, 350, 31, 21));
        north_america_8->setFont(font);
        north_america_8->setCursor(QCursor(Qt::PointingHandCursor));
        north_america_8->setAcceptDrops(false);
        north_america_8->setAutoFillBackground(true);
        north_america_8->setStyleSheet(QStringLiteral(""));
        north_america_8->setInputMethodHints(Qt::ImhNone);
        north_america_8->setAutoRepeat(false);
        north_america_8->setAutoExclusive(false);
        north_america_9 = new QPushButton(centralWidget);
        north_america_9->setObjectName(QStringLiteral("north_america_9"));
        north_america_9->setGeometry(QRect(130, 410, 31, 21));
        north_america_9->setFont(font);
        north_america_9->setCursor(QCursor(Qt::PointingHandCursor));
        north_america_9->setAcceptDrops(false);
        north_america_9->setAutoFillBackground(true);
        north_america_9->setStyleSheet(QStringLiteral(""));
        north_america_9->setInputMethodHints(Qt::ImhNone);
        north_america_9->setAutoRepeat(false);
        north_america_9->setAutoExclusive(false);
        africa = new QPushButton(centralWidget);
        africa->setObjectName(QStringLiteral("africa"));
        africa->setGeometry(QRect(550, 450, 31, 21));
        africa->setFont(font);
        africa->setCursor(QCursor(Qt::PointingHandCursor));
        africa->setAcceptDrops(false);
        africa->setAutoFillBackground(true);
        africa->setStyleSheet(QStringLiteral(""));
        africa->setInputMethodHints(Qt::ImhNone);
        africa->setAutoRepeat(false);
        africa->setAutoExclusive(false);
        africa_2 = new QPushButton(centralWidget);
        africa_2->setObjectName(QStringLiteral("africa_2"));
        africa_2->setGeometry(QRect(670, 440, 31, 21));
        africa_2->setFont(font);
        africa_2->setCursor(QCursor(Qt::PointingHandCursor));
        africa_2->setAcceptDrops(false);
        africa_2->setAutoFillBackground(true);
        africa_2->setStyleSheet(QStringLiteral(""));
        africa_2->setInputMethodHints(Qt::ImhNone);
        africa_2->setAutoRepeat(false);
        africa_2->setAutoExclusive(false);
        africa_3 = new QPushButton(centralWidget);
        africa_3->setObjectName(QStringLiteral("africa_3"));
        africa_3->setGeometry(QRect(650, 550, 31, 21));
        africa_3->setFont(font);
        africa_3->setCursor(QCursor(Qt::PointingHandCursor));
        africa_3->setAcceptDrops(false);
        africa_3->setAutoFillBackground(true);
        africa_3->setStyleSheet(QStringLiteral(""));
        africa_3->setInputMethodHints(Qt::ImhNone);
        africa_3->setAutoRepeat(false);
        africa_3->setAutoExclusive(false);
        africa_4 = new QPushButton(centralWidget);
        africa_4->setObjectName(QStringLiteral("africa_4"));
        africa_4->setGeometry(QRect(710, 560, 31, 21));
        africa_4->setFont(font);
        africa_4->setCursor(QCursor(Qt::PointingHandCursor));
        africa_4->setAcceptDrops(false);
        africa_4->setAutoFillBackground(true);
        africa_4->setStyleSheet(QStringLiteral(""));
        africa_4->setInputMethodHints(Qt::ImhNone);
        africa_4->setAutoRepeat(false);
        africa_4->setAutoExclusive(false);
        africa_5 = new QPushButton(centralWidget);
        africa_5->setObjectName(QStringLiteral("africa_5"));
        africa_5->setGeometry(QRect(660, 630, 31, 21));
        africa_5->setFont(font);
        africa_5->setCursor(QCursor(Qt::PointingHandCursor));
        africa_5->setAcceptDrops(false);
        africa_5->setAutoFillBackground(true);
        africa_5->setStyleSheet(QStringLiteral(""));
        africa_5->setInputMethodHints(Qt::ImhNone);
        africa_5->setAutoRepeat(false);
        africa_5->setAutoExclusive(false);
        africa_6 = new QPushButton(centralWidget);
        africa_6->setObjectName(QStringLiteral("africa_6"));
        africa_6->setGeometry(QRect(770, 600, 31, 21));
        africa_6->setFont(font);
        africa_6->setCursor(QCursor(Qt::PointingHandCursor));
        africa_6->setAcceptDrops(false);
        africa_6->setAutoFillBackground(true);
        africa_6->setStyleSheet(QStringLiteral(""));
        africa_6->setInputMethodHints(Qt::ImhNone);
        africa_6->setAutoRepeat(false);
        africa_6->setAutoExclusive(false);
        europe_1 = new QPushButton(centralWidget);
        europe_1->setObjectName(QStringLiteral("europe_1"));
        europe_1->setGeometry(QRect(490, 170, 31, 21));
        europe_1->setFont(font);
        europe_1->setCursor(QCursor(Qt::PointingHandCursor));
        europe_1->setAcceptDrops(false);
        europe_1->setAutoFillBackground(true);
        europe_1->setStyleSheet(QStringLiteral(""));
        europe_1->setInputMethodHints(Qt::ImhNone);
        europe_1->setAutoRepeat(false);
        europe_1->setAutoExclusive(false);
        europe_2 = new QPushButton(centralWidget);
        europe_2->setObjectName(QStringLiteral("europe_2"));
        europe_2->setGeometry(QRect(550, 190, 31, 21));
        europe_2->setFont(font);
        europe_2->setCursor(QCursor(Qt::PointingHandCursor));
        europe_2->setAcceptDrops(false);
        europe_2->setAutoFillBackground(true);
        europe_2->setStyleSheet(QStringLiteral(""));
        europe_2->setInputMethodHints(Qt::ImhNone);
        europe_2->setAutoRepeat(false);
        europe_2->setAutoExclusive(false);
        europe_3 = new QPushButton(centralWidget);
        europe_3->setObjectName(QStringLiteral("europe_3"));
        europe_3->setGeometry(QRect(630, 130, 31, 21));
        europe_3->setFont(font);
        europe_3->setCursor(QCursor(Qt::PointingHandCursor));
        europe_3->setAcceptDrops(false);
        europe_3->setAutoFillBackground(true);
        europe_3->setStyleSheet(QStringLiteral(""));
        europe_3->setInputMethodHints(Qt::ImhNone);
        europe_3->setAutoRepeat(false);
        europe_3->setAutoExclusive(false);
        europe_4 = new QPushButton(centralWidget);
        europe_4->setObjectName(QStringLiteral("europe_4"));
        europe_4->setGeometry(QRect(560, 260, 31, 21));
        europe_4->setFont(font);
        europe_4->setCursor(QCursor(Qt::PointingHandCursor));
        europe_4->setAcceptDrops(false);
        europe_4->setAutoFillBackground(true);
        europe_4->setStyleSheet(QStringLiteral(""));
        europe_4->setInputMethodHints(Qt::ImhNone);
        europe_4->setAutoRepeat(false);
        europe_4->setAutoExclusive(false);
        europe_5 = new QPushButton(centralWidget);
        europe_5->setObjectName(QStringLiteral("europe_5"));
        europe_5->setGeometry(QRect(620, 310, 31, 21));
        europe_5->setFont(font);
        europe_5->setCursor(QCursor(Qt::PointingHandCursor));
        europe_5->setAcceptDrops(false);
        europe_5->setAutoFillBackground(true);
        europe_5->setStyleSheet(QStringLiteral(""));
        europe_5->setInputMethodHints(Qt::ImhNone);
        europe_5->setAutoRepeat(false);
        europe_5->setAutoExclusive(false);
        europe_6 = new QPushButton(centralWidget);
        europe_6->setObjectName(QStringLiteral("europe_6"));
        europe_6->setGeometry(QRect(630, 260, 31, 21));
        europe_6->setFont(font);
        europe_6->setCursor(QCursor(Qt::PointingHandCursor));
        europe_6->setAcceptDrops(false);
        europe_6->setAutoFillBackground(true);
        europe_6->setStyleSheet(QStringLiteral(""));
        europe_6->setInputMethodHints(Qt::ImhNone);
        europe_6->setAutoRepeat(false);
        europe_6->setAutoExclusive(false);
        europe_7 = new QPushButton(centralWidget);
        europe_7->setObjectName(QStringLiteral("europe_7"));
        europe_7->setGeometry(QRect(690, 250, 31, 21));
        europe_7->setFont(font);
        europe_7->setCursor(QCursor(Qt::PointingHandCursor));
        europe_7->setAcceptDrops(false);
        europe_7->setAutoFillBackground(true);
        europe_7->setStyleSheet(QStringLiteral(""));
        europe_7->setInputMethodHints(Qt::ImhNone);
        europe_7->setAutoRepeat(false);
        europe_7->setAutoExclusive(false);
        australia = new QPushButton(centralWidget);
        australia->setObjectName(QStringLiteral("australia"));
        australia->setGeometry(QRect(1000, 620, 31, 21));
        australia->setFont(font);
        australia->setCursor(QCursor(Qt::PointingHandCursor));
        australia->setAcceptDrops(false);
        australia->setAutoFillBackground(true);
        australia->setStyleSheet(QStringLiteral(""));
        australia->setInputMethodHints(Qt::ImhNone);
        australia->setAutoRepeat(false);
        australia->setAutoExclusive(false);
        australia_2 = new QPushButton(centralWidget);
        australia_2->setObjectName(QStringLiteral("australia_2"));
        australia_2->setGeometry(QRect(1080, 570, 31, 21));
        australia_2->setFont(font);
        australia_2->setCursor(QCursor(Qt::PointingHandCursor));
        australia_2->setAcceptDrops(false);
        australia_2->setAutoFillBackground(true);
        australia_2->setStyleSheet(QStringLiteral(""));
        australia_2->setInputMethodHints(Qt::ImhNone);
        australia_2->setAutoRepeat(false);
        australia_2->setAutoExclusive(false);
        australia_3 = new QPushButton(centralWidget);
        australia_3->setObjectName(QStringLiteral("australia_3"));
        australia_3->setGeometry(QRect(1080, 470, 31, 21));
        australia_3->setFont(font);
        australia_3->setCursor(QCursor(Qt::PointingHandCursor));
        australia_3->setAcceptDrops(false);
        australia_3->setAutoFillBackground(true);
        australia_3->setStyleSheet(QStringLiteral(""));
        australia_3->setInputMethodHints(Qt::ImhNone);
        australia_3->setAutoRepeat(false);
        australia_3->setAutoExclusive(false);
        australia_4 = new QPushButton(centralWidget);
        australia_4->setObjectName(QStringLiteral("australia_4"));
        australia_4->setGeometry(QRect(940, 500, 31, 21));
        australia_4->setFont(font);
        australia_4->setCursor(QCursor(Qt::PointingHandCursor));
        australia_4->setAcceptDrops(false);
        australia_4->setAutoFillBackground(true);
        australia_4->setStyleSheet(QStringLiteral(""));
        australia_4->setInputMethodHints(Qt::ImhNone);
        australia_4->setAutoRepeat(false);
        australia_4->setAutoExclusive(false);
        asia = new QPushButton(centralWidget);
        asia->setObjectName(QStringLiteral("asia"));
        asia->setGeometry(QRect(1020, 110, 31, 21));
        asia->setFont(font);
        asia->setCursor(QCursor(Qt::PointingHandCursor));
        asia->setAcceptDrops(false);
        asia->setAutoFillBackground(true);
        asia->setStyleSheet(QStringLiteral(""));
        asia->setInputMethodHints(Qt::ImhNone);
        asia->setAutoRepeat(false);
        asia->setAutoExclusive(false);
        asia_2 = new QPushButton(centralWidget);
        asia_2->setObjectName(QStringLiteral("asia_2"));
        asia_2->setGeometry(QRect(940, 110, 31, 21));
        asia_2->setFont(font);
        asia_2->setCursor(QCursor(Qt::PointingHandCursor));
        asia_2->setAcceptDrops(false);
        asia_2->setAutoFillBackground(true);
        asia_2->setStyleSheet(QStringLiteral(""));
        asia_2->setInputMethodHints(Qt::ImhNone);
        asia_2->setAutoRepeat(false);
        asia_2->setAutoExclusive(false);
        asia_3 = new QPushButton(centralWidget);
        asia_3->setObjectName(QStringLiteral("asia_3"));
        asia_3->setGeometry(QRect(880, 160, 31, 21));
        asia_3->setFont(font);
        asia_3->setCursor(QCursor(Qt::PointingHandCursor));
        asia_3->setAcceptDrops(false);
        asia_3->setAutoFillBackground(true);
        asia_3->setStyleSheet(QStringLiteral(""));
        asia_3->setInputMethodHints(Qt::ImhNone);
        asia_3->setAutoRepeat(false);
        asia_3->setAutoExclusive(false);
        asia_4 = new QPushButton(centralWidget);
        asia_4->setObjectName(QStringLiteral("asia_4"));
        asia_4->setGeometry(QRect(940, 190, 31, 21));
        asia_4->setFont(font);
        asia_4->setCursor(QCursor(Qt::PointingHandCursor));
        asia_4->setAcceptDrops(false);
        asia_4->setAutoFillBackground(true);
        asia_4->setStyleSheet(QStringLiteral(""));
        asia_4->setInputMethodHints(Qt::ImhNone);
        asia_4->setAutoRepeat(false);
        asia_4->setAutoExclusive(false);
        asia_5 = new QPushButton(centralWidget);
        asia_5->setObjectName(QStringLiteral("asia_5"));
        asia_5->setGeometry(QRect(980, 230, 31, 21));
        asia_5->setFont(font);
        asia_5->setCursor(QCursor(Qt::PointingHandCursor));
        asia_5->setAcceptDrops(false);
        asia_5->setAutoFillBackground(true);
        asia_5->setStyleSheet(QStringLiteral(""));
        asia_5->setInputMethodHints(Qt::ImhNone);
        asia_5->setAutoRepeat(false);
        asia_5->setAutoExclusive(false);
        asia_6 = new QPushButton(centralWidget);
        asia_6->setObjectName(QStringLiteral("asia_6"));
        asia_6->setGeometry(QRect(950, 320, 31, 21));
        asia_6->setFont(font);
        asia_6->setCursor(QCursor(Qt::PointingHandCursor));
        asia_6->setAcceptDrops(false);
        asia_6->setAutoFillBackground(true);
        asia_6->setStyleSheet(QStringLiteral(""));
        asia_6->setInputMethodHints(Qt::ImhNone);
        asia_6->setAutoRepeat(false);
        asia_6->setAutoExclusive(false);
        asia_7 = new QPushButton(centralWidget);
        asia_7->setObjectName(QStringLiteral("asia_7"));
        asia_7->setGeometry(QRect(810, 340, 31, 21));
        asia_7->setFont(font);
        asia_7->setCursor(QCursor(Qt::PointingHandCursor));
        asia_7->setAcceptDrops(false);
        asia_7->setAutoFillBackground(true);
        asia_7->setStyleSheet(QStringLiteral(""));
        asia_7->setInputMethodHints(Qt::ImhNone);
        asia_7->setAutoRepeat(false);
        asia_7->setAutoExclusive(false);
        asia_8 = new QPushButton(centralWidget);
        asia_8->setObjectName(QStringLiteral("asia_8"));
        asia_8->setGeometry(QRect(930, 400, 31, 21));
        asia_8->setFont(font);
        asia_8->setCursor(QCursor(Qt::PointingHandCursor));
        asia_8->setAcceptDrops(false);
        asia_8->setAutoFillBackground(true);
        asia_8->setStyleSheet(QStringLiteral(""));
        asia_8->setInputMethodHints(Qt::ImhNone);
        asia_8->setAutoRepeat(false);
        asia_8->setAutoExclusive(false);
        asia_9 = new QPushButton(centralWidget);
        asia_9->setObjectName(QStringLiteral("asia_9"));
        asia_9->setGeometry(QRect(810, 200, 31, 21));
        asia_9->setFont(font);
        asia_9->setCursor(QCursor(Qt::PointingHandCursor));
        asia_9->setAcceptDrops(false);
        asia_9->setAutoFillBackground(true);
        asia_9->setStyleSheet(QStringLiteral(""));
        asia_9->setInputMethodHints(Qt::ImhNone);
        asia_9->setAutoRepeat(false);
        asia_9->setAutoExclusive(false);
        asia_10 = new QPushButton(centralWidget);
        asia_10->setObjectName(QStringLiteral("asia_10"));
        asia_10->setGeometry(QRect(770, 290, 31, 21));
        asia_10->setFont(font);
        asia_10->setCursor(QCursor(Qt::PointingHandCursor));
        asia_10->setAcceptDrops(false);
        asia_10->setAutoFillBackground(true);
        asia_10->setStyleSheet(QStringLiteral(""));
        asia_10->setInputMethodHints(Qt::ImhNone);
        asia_10->setAutoRepeat(false);
        asia_10->setAutoExclusive(false);
        asia_11 = new QPushButton(centralWidget);
        asia_11->setObjectName(QStringLiteral("asia_11"));
        asia_11->setGeometry(QRect(750, 330, 31, 21));
        asia_11->setFont(font);
        asia_11->setCursor(QCursor(Qt::PointingHandCursor));
        asia_11->setAcceptDrops(false);
        asia_11->setAutoFillBackground(true);
        asia_11->setStyleSheet(QStringLiteral(""));
        asia_11->setInputMethodHints(Qt::ImhNone);
        asia_11->setAutoRepeat(false);
        asia_11->setAutoExclusive(false);
        textEdit = new QTextEdit(centralWidget);
        textEdit->setObjectName(QStringLiteral("textEdit"));
        textEdit->setGeometry(QRect(20, 520, 191, 121));
        ENTER = new QPushButton(centralWidget);
        ENTER->setObjectName(QStringLiteral("ENTER"));
        ENTER->setGeometry(QRect(1100, 720, 75, 23));
        ENTER->setCursor(QCursor(Qt::PointingHandCursor));
        ENTER->setStyleSheet(QStringLiteral("background-color:\"green\""));
        SAVE = new QPushButton(centralWidget);
        SAVE->setObjectName(QStringLiteral("SAVE"));
        SAVE->setGeometry(QRect(1090, 360, 91, 24));
        colorP = new QLabel(centralWidget);
        colorP->setObjectName(QStringLiteral("colorP"));
        colorP->setGeometry(QRect(30, 705, 61, 61));
        colorP->setStyleSheet(QStringLiteral("border-image:url(:/new/Resources/players/green.png)"));
        colorP->setPixmap(QPixmap(QString::fromUtf8(":/new/Resources/players/playerblue.png")));
        colorP->setScaledContents(true);
        NEXT = new QPushButton(centralWidget);
        NEXT->setObjectName(QStringLiteral("NEXT"));
        NEXT->setGeometry(QRect(1010, 720, 75, 23));
        NEXT->setStyleSheet(QStringLiteral("background-color:\"orange\""));
        TROOPS = new QGroupBox(centralWidget);
        TROOPS->setObjectName(QStringLiteral("TROOPS"));
        TROOPS->setGeometry(QRect(1240, 60, 171, 161));
        TROOPS->setAlignment(Qt::AlignCenter);
        MINUS = new QPushButton(TROOPS);
        MINUS->setObjectName(QStringLiteral("MINUS"));
        MINUS->setGeometry(QRect(10, 103, 71, 51));
        MINUS->setStyleSheet(QStringLiteral("border-image:url(:/new/Resources/minus.png)"));
        PLUS = new QPushButton(TROOPS);
        PLUS->setObjectName(QStringLiteral("PLUS"));
        PLUS->setGeometry(QRect(90, 103, 71, 51));
        PLUS->setStyleSheet(QStringLiteral("border-image:url(:/new/Resources/plus.png)"));
        troopsP = new QTextEdit(TROOPS);
        troopsP->setObjectName(QStringLiteral("troopsP"));
        troopsP->setGeometry(QRect(40, 20, 91, 71));
        QFont font1;
        font1.setFamily(QStringLiteral("Rockwell Condensed"));
        font1.setPointSize(26);
        font1.setBold(true);
        font1.setWeight(75);
        troopsP->setFont(font1);
        troopsP->setStyleSheet(QStringLiteral("background-color:\"gray\""));
        groupBox = new QGroupBox(centralWidget);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(400, 700, 461, 101));
        card1 = new QPushButton(groupBox);
        card1->setObjectName(QStringLiteral("card1"));
        card1->setGeometry(QRect(0, 0, 91, 101));
        card1->setStyleSheet(QStringLiteral("border-image:url(:/new/Resources/cards/cardDefault.PNG)"));
        card2 = new QPushButton(groupBox);
        card2->setObjectName(QStringLiteral("card2"));
        card2->setGeometry(QRect(90, 0, 91, 101));
        card2->setStyleSheet(QStringLiteral("border-image:url(:/new/Resources/cards/cardDefault.PNG)"));
        card3 = new QPushButton(groupBox);
        card3->setObjectName(QStringLiteral("card3"));
        card3->setGeometry(QRect(180, 0, 91, 101));
        card3->setStyleSheet(QStringLiteral("border-image:url(:/new/Resources/cards/cardDefault.PNG)"));
        card4 = new QPushButton(groupBox);
        card4->setObjectName(QStringLiteral("card4"));
        card4->setGeometry(QRect(270, 0, 91, 101));
        card4->setStyleSheet(QStringLiteral("border-image:url(:/new/Resources/cards/cardDefault.PNG)"));
        card5 = new QPushButton(groupBox);
        card5->setObjectName(QStringLiteral("card5"));
        card5->setGeometry(QRect(360, 0, 91, 101));
        card5->setStyleSheet(QStringLiteral("border-image:url(:/new/Resources/cards/cardDefault.PNG)"));
        TROOPS_2 = new QGroupBox(centralWidget);
        TROOPS_2->setObjectName(QStringLiteral("TROOPS_2"));
        TROOPS_2->setGeometry(QRect(1240, 440, 171, 161));
        TROOPS_2->setAlignment(Qt::AlignCenter);
        MINUS_2 = new QPushButton(TROOPS_2);
        MINUS_2->setObjectName(QStringLiteral("MINUS_2"));
        MINUS_2->setGeometry(QRect(10, 103, 71, 51));
        MINUS_2->setStyleSheet(QStringLiteral("border-image:url(:/new/Resources/minus.png)"));
        PLUS_2 = new QPushButton(TROOPS_2);
        PLUS_2->setObjectName(QStringLiteral("PLUS_2"));
        PLUS_2->setGeometry(QRect(90, 103, 71, 51));
        PLUS_2->setStyleSheet(QStringLiteral("border-image:url(:/new/Resources/plus.png)"));
        troopsP_2 = new QTextEdit(TROOPS_2);
        troopsP_2->setObjectName(QStringLiteral("troopsP_2"));
        troopsP_2->setGeometry(QRect(40, 20, 91, 71));
        troopsP_2->setFont(font1);
        troopsP_2->setStyleSheet(QStringLiteral("background-color:\"gray\""));
        cubeP_1 = new QLabel(centralWidget);
        cubeP_1->setObjectName(QStringLiteral("cubeP_1"));
        cubeP_1->setGeometry(QRect(1220, 250, 91, 61));
        cubeP_2 = new QLabel(centralWidget);
        cubeP_2->setObjectName(QStringLiteral("cubeP_2"));
        cubeP_2->setGeometry(QRect(1340, 250, 91, 61));
        cubeP2_1 = new QLabel(centralWidget);
        cubeP2_1->setObjectName(QStringLiteral("cubeP2_1"));
        cubeP2_1->setGeometry(QRect(1220, 630, 91, 61));
        cubeP2_2 = new QLabel(centralWidget);
        cubeP2_2->setObjectName(QStringLiteral("cubeP2_2"));
        cubeP2_2->setGeometry(QRect(1340, 630, 91, 61));
        cubeP_3 = new QLabel(centralWidget);
        cubeP_3->setObjectName(QStringLiteral("cubeP_3"));
        cubeP_3->setGeometry(QRect(1270, 330, 91, 61));
        cubeP2_3 = new QLabel(centralWidget);
        cubeP2_3->setObjectName(QStringLiteral("cubeP2_3"));
        cubeP2_3->setGeometry(QRect(1280, 700, 91, 61));
        CONVERT = new QPushButton(centralWidget);
        CONVERT->setObjectName(QStringLiteral("CONVERT"));
        CONVERT->setGeometry(QRect(880, 670, 75, 23));
        CONVERT->setStyleSheet(QStringLiteral("background-color:rgb(94, 255, 250)"));
        playerText = new QTextEdit(centralWidget);
        playerText->setObjectName(QStringLiteral("playerText"));
        playerText->setGeometry(QRect(20, 770, 81, 31));
        stageText = new QTextEdit(centralWidget);
        stageText->setObjectName(QStringLiteral("stageText"));
        stageText->setGeometry(QRect(120, 770, 81, 31));
        STATS = new QPushButton(centralWidget);
        STATS->setObjectName(QStringLiteral("STATS"));
        STATS->setGeometry(QRect(1090, 330, 91, 24));
        SAVE_ALL = new QPushButton(centralWidget);
        SAVE_ALL->setObjectName(QStringLiteral("SAVE_ALL"));
        SAVE_ALL->setGeometry(QRect(1090, 390, 91, 24));
        EXIT = new QPushButton(centralWidget);
        EXIT->setObjectName(QStringLiteral("EXIT"));
        EXIT->setGeometry(QRect(1060, 770, 75, 23));
        EXIT->setCursor(QCursor(Qt::PointingHandCursor));
        EXIT->setStyleSheet(QStringLiteral("background-color:\"red\""));
        asia_12 = new QPushButton(centralWidget);
        asia_12->setObjectName(QStringLiteral("asia_12"));
        asia_12->setGeometry(QRect(1040, 280, 31, 21));
        asia_12->setFont(font);
        asia_12->setCursor(QCursor(Qt::PointingHandCursor));
        asia_12->setAcceptDrops(false);
        asia_12->setAutoFillBackground(true);
        asia_12->setStyleSheet(QStringLiteral(""));
        asia_12->setInputMethodHints(Qt::ImhNone);
        asia_12->setAutoRepeat(false);
        asia_12->setAutoExclusive(false);
        value_cards = new QLabel(centralWidget);
        value_cards->setObjectName(QStringLiteral("value_cards"));
        value_cards->setGeometry(QRect(880, 700, 81, 101));
        value_cards->setStyleSheet(QStringLiteral(" border-image:url(:/new/Resources/golden_horse.jpg)"));
        my_riskClass->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(my_riskClass);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1464, 21));
        my_riskClass->setMenuBar(menuBar);
        mainToolBar = new QToolBar(my_riskClass);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        my_riskClass->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(my_riskClass);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        my_riskClass->setStatusBar(statusBar);

        retranslateUi(my_riskClass);
        QObject::connect(SAVE, SIGNAL(clicked()), my_riskClass, SLOT(SAVE()));
        QObject::connect(NEXT, SIGNAL(clicked()), my_riskClass, SLOT(nextState()));
        QObject::connect(SAVE_ALL, SIGNAL(clicked()), my_riskClass, SLOT(SAVE_ALL()));
        QObject::connect(EXIT, SIGNAL(clicked()), my_riskClass, SLOT(EXIT()));

        QMetaObject::connectSlotsByName(my_riskClass);
    } // setupUi

    void retranslateUi(QMainWindow *my_riskClass)
    {
        my_riskClass->setWindowTitle(QApplication::translate("my_riskClass", "my_risk", 0));
        label->setText(QString());
        south_america_1->setText(QString());
        south_america_2->setText(QString());
        south_america_3->setText(QString());
        south_america_4->setText(QString());
        north_america_1->setText(QString());
        north_america_2->setText(QString());
        north_america_3->setText(QString());
        north_america_4->setText(QString());
        north_america_5->setText(QString());
        north_america_6->setText(QString());
        north_america_7->setText(QString());
        north_america_8->setText(QString());
        north_america_9->setText(QString());
        africa->setText(QString());
        africa_2->setText(QString());
        africa_3->setText(QString());
        africa_4->setText(QString());
        africa_5->setText(QString());
        africa_6->setText(QString());
        europe_1->setText(QString());
        europe_2->setText(QString());
        europe_3->setText(QString());
        europe_4->setText(QString());
        europe_5->setText(QString());
        europe_6->setText(QString());
        europe_7->setText(QString());
        australia->setText(QString());
        australia_2->setText(QString());
        australia_3->setText(QString());
        australia_4->setText(QString());
        asia->setText(QString());
        asia_2->setText(QString());
        asia_3->setText(QString());
        asia_4->setText(QString());
        asia_5->setText(QString());
        asia_6->setText(QString());
        asia_7->setText(QString());
        asia_8->setText(QString());
        asia_9->setText(QString());
        asia_10->setText(QString());
        asia_11->setText(QString());
        ENTER->setText(QApplication::translate("my_riskClass", "ENTER", 0));
        SAVE->setText(QApplication::translate("my_riskClass", "SAVE", 0));
        colorP->setText(QString());
        NEXT->setText(QApplication::translate("my_riskClass", "NEXT", 0));
        TROOPS->setTitle(QApplication::translate("my_riskClass", "MY TROOPS", 0));
        MINUS->setText(QString());
        MINUS->setShortcut(QApplication::translate("my_riskClass", "-", 0));
        PLUS->setText(QString());
        PLUS->setShortcut(QApplication::translate("my_riskClass", "+", 0));
        troopsP->setHtml(QApplication::translate("my_riskClass", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Rockwell Condensed'; font-size:26pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt; font-weight:400;\">12</span></p></body></html>", 0));
        groupBox->setTitle(QString());
        card1->setText(QString());
        card2->setText(QString());
        card3->setText(QString());
        card4->setText(QString());
        card5->setText(QString());
        TROOPS_2->setTitle(QApplication::translate("my_riskClass", "ENEMY TROOPS", 0));
        MINUS_2->setText(QString());
        MINUS_2->setShortcut(QApplication::translate("my_riskClass", "-", 0));
        PLUS_2->setText(QString());
        PLUS_2->setShortcut(QApplication::translate("my_riskClass", "+", 0));
        troopsP_2->setHtml(QApplication::translate("my_riskClass", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Rockwell Condensed'; font-size:26pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt; font-weight:400;\">12</span></p></body></html>", 0));
        cubeP_1->setText(QApplication::translate("my_riskClass", "TextLabel", 0));
        cubeP_2->setText(QApplication::translate("my_riskClass", "TextLabel", 0));
        cubeP2_1->setText(QApplication::translate("my_riskClass", "TextLabel", 0));
        cubeP2_2->setText(QApplication::translate("my_riskClass", "TextLabel", 0));
        cubeP_3->setText(QApplication::translate("my_riskClass", "TextLabel", 0));
        cubeP2_3->setText(QApplication::translate("my_riskClass", "TextLabel", 0));
        CONVERT->setText(QApplication::translate("my_riskClass", "CONVERT", 0));
        STATS->setText(QApplication::translate("my_riskClass", "SAVE STATS", 0));
        SAVE_ALL->setText(QApplication::translate("my_riskClass", "SAVE ALL", 0));
        EXIT->setText(QApplication::translate("my_riskClass", "EXIT", 0));
        asia_12->setText(QString());
        value_cards->setText(QApplication::translate("my_riskClass", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#0055ff;\">1</span></p></body></html>", 0));
    } // retranslateUi

};

namespace Ui {
    class my_riskClass: public Ui_my_riskClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MY_RISK_H
